/// Mock farm data for demo stability.
/// Provides believable, pre-seeded environmental readings.
abstract final class MockFarmData {
  // ─── Rack Status ──────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> racks = [
    {
      'id': 'A',
      'name': 'Rack A',
      'crop': 'Butterhead Lettuce',
      'health': 'healthy',
      'moisture': 82,
      'temperature': 23.5,
      'humidity': 68,
      'lightHours': 16,
      'ph': 6.2,
      'ec': 1.8,
      'daysToHarvest': 7,
      'stage': 'Mature',
      'shelves': 5,
      'diseaseRisk': 5,
      'aiRecommendation':
          'Rack A is performing optimally. Maintain current irrigation schedule and monitor pH stability. '
          'Harvest window opens in 7 days — schedule pickup and prepare packaging.',
      'wateringHistory': [
        {'time': 'Today 6:00 AM', 'duration': '45 sec', 'triggered': 'Auto'},
        {'time': 'Yesterday 6:00 PM', 'duration': '50 sec', 'triggered': 'Auto'},
        {'time': 'Yesterday 6:00 AM', 'duration': '45 sec', 'triggered': 'Manual'},
      ],
      'levels': [
        {
          'level': 1,
          'plantName': 'Butterhead Lettuce',
          'status': 'healthy',
          'moisture': 83,
          'temperature': 23.4,
          'ph': 6.2,
          'ec': 1.8,
          'growthStage': 'Mature',
          'daysToHarvest': 7,
        },
        {
          'level': 2,
          'plantName': 'Butterhead Lettuce',
          'status': 'healthy',
          'moisture': 81,
          'temperature': 23.5,
          'ph': 6.1,
          'ec': 1.7,
          'growthStage': 'Mature',
          'daysToHarvest': 7,
        },
        {
          'level': 3,
          'plantName': 'Butterhead Lettuce',
          'status': 'healthy',
          'moisture': 84,
          'temperature': 23.6,
          'ph': 6.2,
          'ec': 1.8,
          'growthStage': 'Mature',
          'daysToHarvest': 6,
        },
        {
          'level': 4,
          'plantName': 'Butterhead Lettuce',
          'status': 'healthy',
          'moisture': 82,
          'temperature': 23.3,
          'ph': 6.3,
          'ec': 1.9,
          'growthStage': 'Mature',
          'daysToHarvest': 8,
        },
        {
          'level': 5,
          'plantName': 'Butterhead Lettuce',
          'status': 'healthy',
          'moisture': 80,
          'temperature': 23.5,
          'ph': 6.2,
          'ec': 1.8,
          'growthStage': 'Mature',
          'daysToHarvest': 7,
        },
      ],
    },
    {
      'id': 'B',
      'name': 'Rack B',
      'crop': 'Basil',
      'health': 'warning',
      'moisture': 72,
      'temperature': 24.8,
      'humidity': 75,
      'lightHours': 14,
      'ph': 6.8,
      'ec': 2.1,
      'daysToHarvest': 12,
      'stage': 'Vegetative',
      'shelves': 5,
      'diseaseRisk': 32,
      'aiRecommendation':
          'Moisture instability on Rack B. Increase nutrient concentration by 10% and '
          'activate a 30-second irrigation burst now. Target EC 1.8–2.2 and pH 6.0–6.5. Monitor for 2 hours.',
      'wateringHistory': [
        {'time': 'Today 12:08 PM', 'duration': '30 sec', 'triggered': 'Auto'},
        {'time': 'Today 6:00 AM', 'duration': '45 sec', 'triggered': 'Auto'},
        {'time': 'Yesterday 6:00 PM', 'duration': '35 sec', 'triggered': 'Manual'},
      ],
      'levels': [
        {
          'level': 1,
          'plantName': 'Basil',
          'status': 'healthy',
          'moisture': 79,
          'temperature': 24.5,
          'ph': 6.4,
          'ec': 1.9,
          'growthStage': 'Vegetative',
          'daysToHarvest': 12,
        },
        {
          'level': 2,
          'plantName': 'Basil',
          'status': 'healthy',
          'moisture': 77,
          'temperature': 24.7,
          'ph': 6.5,
          'ec': 2.0,
          'growthStage': 'Vegetative',
          'daysToHarvest': 12,
        },
        {
          'level': 3,
          'plantName': 'Basil',
          'status': 'warning',
          'moisture': 62,
          'temperature': 25.2,
          'ph': 7.1,
          'ec': 2.3,
          'growthStage': 'Vegetative',
          'daysToHarvest': 15,
        },
        {
          'level': 4,
          'plantName': 'Basil',
          'status': 'healthy',
          'moisture': 76,
          'temperature': 24.8,
          'ph': 6.4,
          'ec': 2.0,
          'growthStage': 'Vegetative',
          'daysToHarvest': 12,
        },
        {
          'level': 5,
          'plantName': 'Basil',
          'status': 'healthy',
          'moisture': 78,
          'temperature': 24.6,
          'ph': 6.3,
          'ec': 1.9,
          'growthStage': 'Vegetative',
          'daysToHarvest': 12,
        },
      ],
    },
    {
      'id': 'C',
      'name': 'Rack C',
      'crop': 'Spinach',
      'health': 'healthy',
      'moisture': 85,
      'temperature': 21.8,
      'humidity': 64,
      'lightHours': 14,
      'ph': 6.1,
      'ec': 1.7,
      'daysToHarvest': 9,
      'stage': 'Vegetative',
      'shelves': 5,
      'diseaseRisk': 6,
      'aiRecommendation':
          'Rack C is stable. Moisture and nutrient levels are within optimal range. '
          'No corrective action needed. Harvest window in 9 days.',
      'wateringHistory': [
        {'time': 'Today 9:00 AM', 'duration': '50 sec', 'triggered': 'Auto'},
        {'time': 'Yesterday 9:00 PM', 'duration': '48 sec', 'triggered': 'Auto'},
        {'time': 'Yesterday 9:00 AM', 'duration': '50 sec', 'triggered': 'Auto'},
      ],
      'levels': [
        {
          'level': 1,
          'plantName': 'Spinach',
          'status': 'healthy',
          'moisture': 86,
          'temperature': 21.7,
          'ph': 6.1,
          'ec': 1.7,
          'growthStage': 'Vegetative',
          'daysToHarvest': 9,
        },
        {
          'level': 2,
          'plantName': 'Spinach',
          'status': 'healthy',
          'moisture': 85,
          'temperature': 21.8,
          'ph': 6.0,
          'ec': 1.6,
          'growthStage': 'Vegetative',
          'daysToHarvest': 9,
        },
        {
          'level': 3,
          'plantName': 'Spinach',
          'status': 'healthy',
          'moisture': 84,
          'temperature': 21.9,
          'ph': 6.1,
          'ec': 1.7,
          'growthStage': 'Vegetative',
          'daysToHarvest': 10,
        },
        {
          'level': 4,
          'plantName': 'Spinach',
          'status': 'healthy',
          'moisture': 86,
          'temperature': 21.6,
          'ph': 6.2,
          'ec': 1.8,
          'growthStage': 'Vegetative',
          'daysToHarvest': 9,
        },
        {
          'level': 5,
          'plantName': 'Spinach',
          'status': 'healthy',
          'moisture': 85,
          'temperature': 21.8,
          'ph': 6.1,
          'ec': 1.7,
          'growthStage': 'Vegetative',
          'daysToHarvest': 8,
        },
      ],
    },
  ];

  static Map<String, dynamic> rackById(String rackId) {
    return racks.firstWhere(
      (rack) => (rack['id'] as String).toUpperCase() == rackId.toUpperCase(),
      orElse: () => racks.first,
    );
  }

  // ─── Global Farm Metrics ──────────────────────────────────────────────────
  static const Map<String, dynamic> farmMetrics = {
    'overallHealth': 'healthy',
    'healthScore': 87,
    'activeRacks': 3,
    'totalAlerts': 2,
    'criticalAlerts': 0,
    'avgTemperature': 23.4,
    'avgHumidity': 69.0,
    'waterTankLevel': 34,
    'powerUsageKw': 3.8,
    'aiConfidence': 91,
  };

  // ─── AI Activity Log ──────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> aiActivity = [
    {
      'icon': '🧠',
      'title': 'AI activated irrigation',
      'subtitle': 'Scheduled optimisation for Rack B',
      'timeAgo': '12m ago',
      'type': 'action',
    },
    {
      'icon': '💡',
      'title': 'LED brightness adjusted',
      'subtitle': 'Spectrum tuned for flowering phase',
      'timeAgo': '1h ago',
      'type': 'automation',
    },
    {
      'icon': '🌡️',
      'title': 'Temperature anomaly resolved',
      'subtitle': 'HVAC recalibrated — Rack B, Level 3',
      'timeAgo': '3h ago',
      'type': 'resolved',
    },
    {
      'icon': '📅',
      'title': 'Harvest prediction updated',
      'subtitle': 'Rack A lettuce ready in 7 days',
      'timeAgo': '6h ago',
      'type': 'prediction',
    },
  ];

  // ─── Mock Alerts ──────────────────────────────────────────────────────────
  static const List<Map<String, dynamic>> alerts = [
    {
      'id': '1',
      'type': 'warning',
      'title': 'Water Tank Low',
      'description': 'Main reservoir at 34%. Refill recommended within 12 hours.',
      'rack': null,
      'timestamp': '2 min ago',
      'isRead': false,
    },
    {
      'id': '2',
      'type': 'info',
      'title': 'pH Slightly High — Rack B',
      'description': 'pH reading 6.8, optimal range 6.0–6.5. AI adjusting nutrient solution.',
      'rack': 'B',
      'timestamp': '15 min ago',
      'isRead': false,
    },
    {
      'id': '3',
      'type': 'success',
      'title': 'Harvest Ready Soon — Rack A',
      'description': 'Butterhead Lettuce approaching optimal harvest parameters. Schedule pickup.',
      'rack': 'A',
      'timestamp': '1 hour ago',
      'isRead': true,
    },
    {
      'id': '4',
      'type': 'warning',
      'title': 'Moisture Low — Rack B',
      'description': 'Rack B moisture trending 14% below optimal. Irrigation cycle initiated.',
      'rack': 'B',
      'timestamp': '2 hours ago',
      'isRead': true,
    },
  ];

  // ─── Tag → Single Plant Mapping ───────────────────────────────────────────
  static const Map<int, Map<String, dynamic>> tagToPlant = {
    0: {
      'plantId': 'RA-L3-P01',
      'rackId': 'A',
      'level': 3,
      'health': 92,
      'status': 'healthy',
      'issue': '',
      'confidence': 0,
      'recommendation': '',
      'zoomAsset': 'assets/images/zoom3.png',
      'statusAsset': 'assets/images/healthy.png',
      'crop': 'Butterhead Lettuce',
      'stage': 'Mature',
      'daysToHarvest': 7,
      'diseaseRisk': 5,
      'growthPercent': 75,
    },
    1: {
      'plantId': 'RB-L3-P02',
      'rackId': 'B',
      'level': 3,
      'health': 74,
      'status': 'warning',
      'issue': 'Low Moisture & Elevated pH',
      'confidence': 91,
      'recommendation': 'Increase irrigation frequency. Adjust nutrient solution to lower pH to 6.0–6.5.',
      'zoomAsset': 'assets/images/zoom3.png',
      'statusAsset': 'assets/images/unhealthy.png',
      'crop': 'Basil',
      'stage': 'Vegetative',
      'daysToHarvest': 15,
      'diseaseRisk': 36,
      'growthPercent': 68,
    },
    2: {
      'plantId': 'RB-L5-P01',
      'rackId': 'B',
      'level': 5,
      'health': 91,
      'status': 'healthy',
      'issue': '',
      'confidence': 0,
      'recommendation': '',
      'zoomAsset': 'assets/images/zoom5.png',
      'statusAsset': 'assets/images/healthy.png',
      'crop': 'Basil',
      'stage': 'Vegetative',
      'daysToHarvest': 12,
      'diseaseRisk': 8,
      'growthPercent': 72,
    },
  };

  // ─── Rack B Plant-Level Data ──────────────────────────────────────────────
  // Only level 3 has individual plant monitoring (the problem shelf).
  static const Map<int, List<Map<String, dynamic>>> rackBPlantLevels = {
    3: [
      {'id': 'B-L3-P01', 'health': 88, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom3.png'},
      {'id': 'B-L3-P02', 'health': 74, 'status': 'warning', 'issue': 'Low Moisture & Elevated pH', 'confidence': 91, 'recommendation': 'Increase irrigation frequency and adjust pH to 6.0–6.5', 'zoomAsset': 'assets/images/zoom3.png'},
      {'id': 'B-L3-P03', 'health': 91, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom3.png'},
      {'id': 'B-L3-P04', 'health': 85, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom3.png'},
      {'id': 'B-L3-P05', 'health': 90, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom3.png'},
    ],
    5: [
      {'id': 'B-L5-P01', 'health': 93, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom5.png'},
      {'id': 'B-L5-P02', 'health': 91, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom5.png'},
      {'id': 'B-L5-P03', 'health': 89, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom5.png'},
      {'id': 'B-L5-P04', 'health': 94, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom5.png'},
      {'id': 'B-L5-P05', 'health': 92, 'status': 'healthy', 'issue': '', 'confidence': 0, 'recommendation': '', 'zoomAsset': 'assets/images/zoom5.png'},
    ],
  };

  // ─── Mock Chat Responses ──────────────────────────────────────────────────
  static const Map<String, String> chatWorkflows = {
    'rack b': 'Rack B is currently showing moisture instability at 72% (optimal: 82%). I\'ve already activated an irrigation cycle. pH is slightly elevated at 6.8 — I\'m adjusting the nutrient solution mix. Basil in this rack is 12 days from harvest.',
    'harvest': 'Current harvest predictions:\n\n🌿 Rack A (Butterhead Lettuce) — 7 days\n🌿 Rack B (Basil) — 12 days\n🥬 Rack C (Spinach) — 9 days\n\nWould you like me to schedule calendar reminders for these harvest dates?',
    'temperature': 'Current temperature readings:\n\n• Rack A: 23.5°C ✅ Optimal\n• Rack B: 24.8°C ⚠️ Slightly elevated\n• Rack C: 21.8°C ✅ Optimal\n\nRack B temperature spike detected 45 minutes ago — HVAC cycle adjusted. Monitoring continuously.',
    'irrigation': 'Irrigation status across all racks:\n\n• Rack A: Last irrigated 2h ago — Next in 4h\n• Rack B: Active irrigation cycle — started 12 min ago\n• Rack C: Last irrigated 3h ago — Next in 3h\n\nAll drip systems operating normally. Water consumption today: 14.2L (within optimal range).',
    'default': 'I\'m continuously monitoring all 3 racks. Current farm health score is 87/100. Two active alerts require attention: Water Tank at 34% and Rack B pH elevation. I\'ve already initiated corrective actions. What would you like to know more about?',
  };
}
